(() => {
  const allVehicles = (window.VISION_DATA || []).map((v, i) => ({...v, id:i+1, speedNum:Number.parseInt(v.speed,10)||0}));
  const state = {page:1,pageSize:8,view:'all',search:'',unit:'',movement:'',status:'',user:'',section:'dashboard'};
  const $ = id => document.getElementById(id);
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const visible = () => allVehicles.filter(v => {
    const haystack=[v.unit,v.fleet,v.plate,v.driver,v.point,v.location,v.status].join(' ').toLowerCase();
    if(state.search && !haystack.includes(state.search.toLowerCase())) return false;
    if(state.unit && v.unit !== state.unit) return false;
    if(state.movement && v.movement !== state.movement) return false;
    if(state.status && !v.status.toLowerCase().includes(state.status.toLowerCase())) return false;
    if(state.view==='operational' && !/trânsito|parado/i.test(v.status)) return false;
    if(state.view==='exceptions' && !/aguardando|travado|risco/i.test(v.status)) return false;
    return true;
  });
  function classify(v){if(/aguardando/i.test(v.status))return 'waiting';if(/parado/i.test(v.movement))return 'stopped';if(/trânsito/i.test(v.status))return 'moving';return 'other'}
  function renderMetrics(){const counts={total:allVehicles.length,moving:allVehicles.filter(v=>classify(v)==='moving').length,stopped:allVehicles.filter(v=>classify(v)==='stopped').length,waiting:allVehicles.filter(v=>classify(v)==='waiting').length,loaded:allVehicles.filter(v=>/carregado/i.test(v.status)).length,empty:allVehicles.filter(v=>/vazio/i.test(v.status)).length,alerts:78};$('metricCards').innerHTML=[['TOTAL DE VEÍCULOS',counts.total,'100% da seleção'],['EM TRÂNSITO',counts.moving,'26% da seleção'],['PARADOS',counts.stopped,'8% da seleção'],['AGUARDANDO',counts.waiting,'atenção operacional'],['CARREGADOS',counts.loaded,'situação conhecida'],['VAZIOS',counts.empty,'em deslocamento'],['ALERTAS',counts.alerts,'eventos monitorados']].map(x=>`<div class="metric"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('');$('alertCount').textContent=counts.alerts;const groups=[['moving','Em trânsito'],['stopped','Parados'],['waiting','Aguardando'],['other','Outros']];$('pulseBar').innerHTML=groups.map(([key])=>`<span class="pulse-segment" style="width:${Math.max(4,allVehicles.filter(v=>classify(v)===key).length/allVehicles.length*100)}%"></span>`).join('');$('pulseLegend').innerHTML=groups.map(([key,label])=>`<span><b>${allVehicles.filter(v=>classify(v)===key).length}</b> ${label}</span>`).join('')}
  function renderTable(){const items=visible(),pages=Math.max(1,Math.ceil(items.length/state.pageSize));state.page=Math.min(state.page,pages);const start=(state.page-1)*state.pageSize;const pageItems=items.slice(start,start+state.pageSize);$('vehicleRows').innerHTML=pageItems.length?pageItems.map(v=>`<tr><td><strong>${esc(v.unit)}</strong></td><td>${esc(v.fleet)}</td><td><strong>${esc(v.plate)}</strong></td><td>${esc(v.driver)}</td><td>${esc(v.movement)}</td><td>${esc(v.speed)}</td><td><span class="status ${/aguardando|parado/i.test(v.status)?'alert':''}">${esc(v.status)}</span></td><td>${esc(v.point)}</td><td title="${esc(v.location)}">${esc(v.location.slice(0,58))}${v.location.length>58?'…':''}</td><td><span class="status">${esc(v.tracker)}</span></td></tr>`).join(''):`<tr><td colspan="10" class="muted">Nenhum veículo encontrado para os filtros selecionados.</td></tr>`;$('tableSummary').textContent=`${items.length} veículos encontrados`;$('pageLabel').textContent=`Página ${state.page} de ${pages}`;['firstPage','prevPage'].forEach(id=>$(id).disabled=state.page===1);['nextPage','lastPage'].forEach(id=>$(id).disabled=state.page===pages)}
  function renderAlerts(){const alerts=[['78','Alertas monitorados','Sinais que merecem acompanhamento na operação.'],['4','Veículos em fábrica','Aguardando carregamento ou liberação.'],['3','Veículos parados','Movimento parado na última coleta.'],['2','Aguardando descarga','Operações com permanência acima do esperado.'],['1','Rastreador travado','Última posição pode estar desatualizada.'],['0','Áreas de risco','Nenhuma área adicional no recorte local.']];$('alertGrid').innerHTML=alerts.map(x=>`<article class="alert-card"><strong>${x[0]}</strong><h3>${x[1]}</h3><span>${x[2]}</span></article>`).join('')}
  function switchSection(section){state.section=section;document.querySelectorAll('.section-view').forEach(el=>el.classList.add('hidden'));$(section+'Section').classList.remove('hidden');document.querySelectorAll('.nav-button[data-section]').forEach(b=>b.classList.toggle('active',b.dataset.section===section));if(section==='alerts')renderAlerts()}
  function bind(){ $('loginForm').addEventListener('submit',e=>{e.preventDefault();state.user=$('loginUser').value.trim()||'Visitante';localStorage.setItem('vision-local-user',state.user);$('welcomeName').textContent=`Que bom ter você por aqui, ${state.user.split(/\s+/)[0]}.`;$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');renderAll()});$('logoutButton').onclick=()=>{localStorage.removeItem('vision-local-user');$('appView').classList.add('hidden');$('loginView').classList.remove('hidden')};document.querySelectorAll('.nav-button[data-section]').forEach(b=>b.onclick=()=>switchSection(b.dataset.section));document.querySelectorAll('.view-filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.view-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.view=b.dataset.view;state.page=1;renderTable()});$('searchInput').oninput=e=>{state.search=e.target.value;state.page=1;renderTable()};$('unitSelect').onchange=e=>{state.unit=e.target.value;state.page=1;renderTable()};$('movementSelect').onchange=e=>{state.movement=e.target.value;state.page=1;renderTable()};$('statusSelect').onchange=e=>{state.status=e.target.value;state.page=1;renderTable()};$('clearFilters').onclick=()=>{state.search=state.unit=state.movement=state.status='';$('searchInput').value='';$('unitSelect').value='';$('movementSelect').value='';$('statusSelect').value='';state.page=1;renderTable()};$('pageSize').onchange=e=>{state.pageSize=Number(e.target.value);state.page=1;renderTable()};$('firstPage').onclick=()=>{state.page=1;renderTable()};$('prevPage').onclick=()=>{state.page--;renderTable()};$('nextPage').onclick=()=>{state.page++;renderTable()};$('lastPage').onclick=()=>{state.page=Math.ceil(visible().length/state.pageSize);renderTable()};document.querySelectorAll('.back-dashboard').forEach(b=>b.onclick=()=>switchSection('dashboard'));$('compactToggle').onchange=e=>{document.body.classList.toggle('compact-mode',e.target.checked);localStorage.setItem('vision-compact',e.target.checked)};$('darkToggle').onchange=e=>{document.body.classList.toggle('dark-mode',e.target.checked);localStorage.setItem('vision-dark',e.target.checked)};$('resetVisual').onclick=()=>{document.body.classList.remove('compact-mode','dark-mode');$('compactToggle').checked=false;$('darkToggle').checked=false;localStorage.removeItem('vision-compact');localStorage.removeItem('vision-dark')}}
  function renderAll(){const units=[...new Set(allVehicles.map(v=>v.unit))].sort();$('unitSelect').innerHTML='<option value="">Todas as unidades</option>'+units.map(u=>`<option>${esc(u)}</option>`).join('');renderMetrics();renderTable();$('compactToggle').checked=localStorage.getItem('vision-compact')==='true';$('darkToggle').checked=localStorage.getItem('vision-dark')==='true';document.body.classList.toggle('compact-mode',$('compactToggle').checked);document.body.classList.toggle('dark-mode',$('darkToggle').checked)}
  bind();const saved=localStorage.getItem('vision-local-user');if(saved){$('loginUser').value=saved;$('loginPassword').value='local';$('welcomeName').textContent=`Que bom ter você por aqui, ${saved.split(/\s+/)[0]}.`;$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');renderAll()}
})();
