window.VISION_DATA = [
  {
    "unit": "CURITIBA",
    "fleet": "71001",
    "plate": "ABZ3I36",
    "driver": "LUIZ ARTUR C",
    "movement": "Parado",
    "speed": "0 km/h",
    "status": "Parado carregado Manual",
    "point": "MULTILIT",
    "location": "av juscelino kubitschek de oliveira - 0 a 13723 - 81170000 - curitiba - PR",
    "eta": "—",
    "tracker": "Atualizado",
    "position": "30/09/2026, 13:37:09"
  },
  {
    "unit": "CURITIBA",
    "fleet": "71101",
    "plate": "DPG1B01",
    "driver": "MARCIO JOSE",
    "movement": "Rodando",
    "speed": "66 km/h",
    "status": "Em trânsito carregado",
    "point": "VOTORANTIM FÁBRICA 1 RBS",
    "location": "br-277 - guaraniacu - pr - 85400-000 - brazil",
    "eta": "—",
    "tracker": "Atualizado",
    "position": "30/09/2026, 14:05:11"
  },
  {
    "unit": "CURITIBA",
    "fleet": "71102",
    "plate": "EKU1B02",
    "driver": "GILBERTO DE",
    "movement": "Rodando",
    "speed": "55 km/h",
    "status": "Em trânsito vazio",
    "point": "EPR LITORAL S. A. PLATINA",
    "location": "rodovia governador parigot de souza - santo antonio da platina - pr No trajeto · 0% · destino: EPR LITORAL CAMBARA",
    "eta": "—",
    "tracker": "Atualizado",
    "position": "30/09/2026, 14:05:48"
  },
  {
    "unit": "CURITIBA",
    "fleet": "71103",
    "plate": "FKP1B03",
    "driver": "ADRIANO OLIV",
    "movement": "Rodando",
    "speed": "61 km/h",
    "status": "Em trânsito vazio",
    "point": "CONSTRUTORA GASPAR",
    "location": "rod br-116 - 0 a 0 - miracatu - SP",
    "eta": "—",
    "tracker": "Atualizado",
    "position": "30/09/2026, 14:01:48"
  },
  {
    "unit": "CURITIBA",
    "fleet": "71104",
    "plate": "FZL1B04",
    "driver": "LUZIMAR BALD",
    "movement": "Rodando",
    "speed": "67 km/h",
    "status": "Em trânsito carregado",
    "point": "SUPREMO",
    "location": "rodovia governador mario covas - torres - rs Nenhuma rota ativa para SUPREMO → CONCRESERV — PORTO ALEGRE. Confira se a rota usa os mesmos pontos do veículo. Em trânsito cliente · 75% · destino: CONCRESERV — PORTO ALEGRE",
    "eta": "Previsão: 30/09/2026, 17:09:55 154 km · CONCRESERV — PORTO ALEGRE · distância geográfica",
    "tracker": "Atualizado",
    "position": "30/09/2026, 14:05:14"
  },
  {
    "unit": "APIAI",
    "fleet": "71105",
    "plate": "TJO1B05",
    "driver": "OZEIL MORATO",
    "movement": "Parado",
    "speed": "0 km/h",
    "status": "Aguardando descarga",
    "point": "LIGHTWALL — RIO CLARO",
    "location": "rua Um Jn - Jardim Guanabara - Rio Claro - Sp - 13502-414 - Brasil",
    "eta": "30/09/2026, 01:40:59",
    "tracker": "Atualizado",
    "position": "30/09/2026, 13:37:57"
  },
  {
    "unit": "CURITIBA",
    "fleet": "71107",
    "plate": "SHM1B07",
    "driver": "ELIEZER JERE",
    "movement": "Rodando",
    "speed": "74 km/h",
    "status": "Aguardando descarga",
    "point": "CONCREFORT - MANDAGUARI",
    "location": "rodovia herminio pennacchi - mandaguari - pr",
    "eta": "30/09/2026, 10:41:56",
    "tracker": "Atualizado",
    "position": "30/09/2026, 14:05:14"
  },
  {
    "unit": "CURITIBA",
    "fleet": "71110",
    "plate": "SHM1B10",
    "driver": "LUIZ ERNESTO",
    "movement": "Rodando",
    "speed": "81 km/h",
    "status": "Em trânsito carregado",
    "point": "SUPREMO",
    "location": "via marginal da rod br-101 - 0 a 5560 - 88780000 - imbituba - SC Nenhuma rota ativa para SUPREMO → CONCRESERV — PORTO ALEGRE. Confira se a rota usa os mesmos pontos do veículo. Em trânsito cliente · 50% · destino: CONCRESERV — PORTO ALEGRE",
    "eta": "Previsão: 30/09/2026, 20:23:18 315 km · CONCRESERV — PORTO ALEGRE · distância geográfica",
    "tracker": "Atualizado",
    "position": "30/09/2026, 14:05:15"
  },
  {
    "unit": "CURITIBA",
    "fleet": "71112",
    "plate": "CCU1B12",
    "driver": "RAFAEL DO AMARAL",
    "movement": "Rodando",
    "speed": "18 km/h",
    "status": "Em trânsito carregado",
    "point": "INTERCEMENT APIAI",
    "location": "r cerro azul - 1253 a 838 - 83410000 - colombo - PR Nenhuma rota ativa para INTERCEMENT APIAI → BLOCKBUILDING - PINHAIS. Confira se a rota usa os mesmos pontos do veículo. Em trânsito cliente · 71% · destino: BLOCKBUILDING - PINHAIS",
    "eta": "Chegada próxima: 30/09/2026, 14:14:59 8 km · BLOCKBUILDING - PINHAIS · distância geográfica",
    "tracker": "Atualizado",
    "position": "30/09/2026, 14:05:55"
  },
  {
    "unit": "CURITIBA",
    "fleet": "71114",
    "plate": "QSQ1B14",
    "driver": "MAYCON WILLI",
    "movement": "Rodando",
    "speed": "73 km/h",
    "status": "Em trânsito carregado",
    "point": "VOTORANTIM FABRICA 1 - RBS",
    "location": "ers-135 - erebango - rs - 99920-000 - brasil",
    "eta": "—",
    "tracker": "Atualizado",
    "position": "30/09/2026, 14:05:23"
  },
  {
    "unit": "APIAI",
    "fleet": "71115",
    "plate": "QSW1B15",
    "driver": "SERGIO HENRI",
    "movement": "Rodando",
    "speed": "72 km/h",
    "status": "Em trânsito vazio",
    "point": "INKOR - IMBITUBA",
    "location": "praia de fora - palhoca - sc - 88138-380 - brasil",
    "eta": "—",
    "tracker": "Atualizado",
    "position": "30/09/2026, 14:05:55"
  },
  {
    "unit": "CURITIBA",
    "fleet": "71117",
    "plate": "UDC1B17",
    "driver": "JEFERSON NUN",
    "movement": "Parado",
    "speed": "0 km/h",
    "status": "Parado carregado",
    "point": "INTERCEMENT APIAI",
    "location": "rod Do Cafe - Lot Sao Jose - Campo Largo - Pr - Brazil Nenhuma rota ativa para INTERCEMENT APIAI → INKOR — GUAÍRA. Confira se a rota usa os mesmos pontos do veículo. No trajeto · 9% · destino: INKOR — GUAÍRA",
    "eta": "Previsão: 01/10/2026, 00:04:11 501 km · INKOR — GUAÍRA · distância geográfica",
    "tracker": "Atualizado",
    "position": "30/09/2026, 14:02:36"
  },
  {
    "unit": "CURITIBA",
    "fleet": "71118",
    "plate": "SHY2B18",
    "driver": "JEAN CARLOS",
    "movement": "Rodando",
    "speed": "9 km/h",
    "status": "Aguardando descarga Manual",
    "point": "VOTORANTIM FABRICA 1 - RBS",
    "location": "rodovia melo peixoto - cambara - pr No trajeto · 0% · destino: EPR LITORAL CAMBARA",
    "eta": "29/09/2026, 19:49:45",
    "tracker": "Atualizado",
    "position": "30/09/2026, 13:17:33"
  },
  {
    "unit": "CURITIBA",
    "fleet": "71119",
    "plate": "UOG1B19",
    "driver": "NILSON JOSE",
    "movement": "Parado",
    "speed": "0 km/h",
    "status": "Parado vazio",
    "point": "CASTILHO — PALMEIRA",
    "location": "rodovia Joao Chede - Palmeira - Pr",
    "eta": "—",
    "tracker": "Travado",
    "position": "30/09/2026, 06:48:04"
  },
  {
    "unit": "CURITIBA",
    "fleet": "71120",
    "plate": "SHY2B20",
    "driver": "ALEX FABIANO",
    "movement": "Parado",
    "speed": "0 km/h",
    "status": "Aguardando descarga",
    "point": "HIPERMIX - COLOMBO",
    "location": "r Fortunato Taverna - 147 A 150 - 83413000 - colombo - PR",
    "eta": "30/09/2026, 08:15:36",
    "tracker": "Atualizado",
    "position": "30/09/2026, 14:05:21"
  },
  {
    "unit": "CURITIBA",
    "fleet": "71121",
    "plate": "BYW1B21",
    "driver": "ALEX SANDRO",
    "movement": "Parado",
    "speed": "0 km/h",
    "status": "Em trânsito carregado",
    "point": "INTERCEMENT APIAI",
    "location": "r Nove - 57 - Ourinhos - Sp - Brazil Rota inativa: INTERCEMENT APIAI → CONTERSOLO — MANDAGUAÇU. Ative a rota cadastrada. Em trânsito cliente · 35% · destino: CONTERSOLO — MANDAGUAÇU",
    "eta": "Previsão: 30/09/2026, 18:45:41 233 km · CONTERSOLO — MANDAGUAÇU · distância geográfica",
    "tracker": "Atualizado",
    "position": "30/09/2026, 14:05:50"
  }
];
